### ISSUE TITLE
Have option to choose more than one item in parameter type 

### ISSUE THREAD

**Issue by joonseokii** [aquarium-bio/issues#16]

**Comment by joonseokii** [comment]
Get an array of choices.

**Comment by klavins** [comment]
Ok, this has been implemented. If have a parameter p whose type is

{ 
  "type": "number",
  "choices": [ 1,2,3 ]
}

you get a select on the launch page. The value of your parameter for thread i will be

  o.threads[i].parameter.p

and will be a number. If you do

{ 
  "type": "number",
  "choices": [ 1,2,3 ],
  "multiple": true
}

you get a multi select on the launch page. The value of your parameter for thread i will be

  o.threads[i].parameter.p

and will be a and array of numbers.
