### ISSUE TITLE
Sample datatype values can not be saved in the folder interface when creating or editing samples

### ISSUE THREAD

**Issue by sunshineyyy** [aquarium-bio/issues#30]
Devin tried to create a primer in the new folder interface and can not save the overhang or annealing sequences. I tested on my side and can not save any datatype values for samples in the folder interface whether creating new samples or editing old samples. This happens on production server v1042 for both Matrix Genetics and Klavins Lab.

**Comment by sylvainsf** [comment]
Fixed, soon to be deployed.
