### ISSUE TITLE
µ does not display well in task notifications

### ISSUE THREAD

**Issue by sunshineyyy** [aquarium-bio/issues#8]
The character µ does not display well in task notifications whereas it displays without problem in protocols. I used the exact same character in both contexts.

**Comment by klavins** [comment]
Did you try using .html_safe on the string you are sending to notify?

**Comment by sunshineyyy** [comment]
I fixed this. I had two places using a wrong µ character (one probably does not have correct encoding), I fixed one of them and forgot about the other. So this is not a problem on your side. I am closing it.
